// Generated by CoffeeScript 1.6.2
(function() {
  var fs, hljs, parser, renderer, rendererOptions, rs;

  rs = require('robotskirt');

  hljs = require('highlight.js');

  fs = require('fs');

  renderer = new rs.HtmlRenderer([rs.HTML_TOC]);

  renderer.blockcode = function(code, lang) {
    if (lang == null) {
      return "<pre>" + (rs.houdini.escapeHTML(code)) + "</pre>";
    } else {
      return "<pre>" + (hljs.highlight(lang, code)) + "</pre>";
    }
  };

  rendererOptions = [rs.EXT_FENCED_CODE, rs.EXT_NO_INTRA_EMPHASIS, rs.EXT_AUTOLINK, rs.EXT_STRIKETHROUGH, rs.EXT_LAX_HTML_BLOCKS, rs.EXT_SUPERSCRIPT, rs.EXT_TABLES];

  parser = new rs.Markdown(renderer, rendererOptions);

  module.exports.render = function(filename, options, callback) {
    if (options == null) {
      options = {};
    }
    if (arguments.length === 2) {
      callback = arguments[1];
      options = {};
    }
    return fs.readFile(filename, function(err, data) {
      var html;

      if (err) {
        callback(err, null);
      }
      html = rs.smartypantsHtml(parser.render(data.toString()));
      return callback(null, html);
    });
  };

}).call(this);
