// Generated by CoffeeScript 1.6.2
(function() {
  var fs, hljs, parser, renderer, rendererOptions, rs;

  rs = require('robotskirt');

  hljs = require('highlight.js');

  fs = require('fs');

  renderer = new rs.HtmlRenderer([rs.HTML_TOC]);

  renderer.blockcode = function(code, lang) {
    if (lang == null) {
      return "<pre><code>" + (rs.houdini.escapeHTML(code)) + "</code></pre>";
    } else {
      return "<pre><code>" + (hljs.highlight(lang, code).value) + "</code></pre>";
    }
  };

  rendererOptions = [rs.EXT_FENCED_CODE, rs.EXT_NO_INTRA_EMPHASIS, rs.EXT_AUTOLINK, rs.EXT_STRIKETHROUGH, rs.EXT_LAX_HTML_BLOCKS, rs.EXT_SUPERSCRIPT, rs.EXT_TABLES];

  parser = new rs.Markdown(renderer, rendererOptions);

  module.exports.render = function(data, options) {
    if (options == null) {
      options = {};
    }
    return rs.smartypantsHtml(parser.render(data.toString()));
  };

}).call(this);
